account/urls.py
from django.contrib import admin
from django.urls import path, include
from account import views
#from app1 import views
urlpatterns = [
    # path('',views.index, name='index'),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('login/',views.login_, name='login'),
    path('register/',views.register,name="register"),
    path('logout/',views.logout_, name='logout'),
    # path('profile/',views.profile,name='profile'),

]

blog/urls.py
from django.contrib import admin
from django.urls import path
from blog import views
urlpatterns = [
    path('',views.blogs,name='blogs'),

    path('create_blog/',views.createBlog,name='create_blog'),
    path('update_blog/<slug:slug>/',views.updateBlog, name='update_blog'),
    path('delete_blog/<slug:slug>/',views.deleteBlog, name='delete_blog'),
    path('<slug:slug>/',views.blog, name='slug'),


]

coderpapa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('account/', include('account.urls')),
    path('turistingo/', include('turistingo.urls')),
    path('projects/', include('myprojects.urls')),
    path('blogs/',include('blog.urls')),
    path('wineshop/',include('wineshop.urls')),
    path('carprice/',include('carprice.urls')),
    path('ques/',include('objectiveQues.urls')),
    path('', include('main.urls')),
    path('profile/', include('portfolio.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('tutorials/', include('tutorial.urls')),

    #1
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="password_reset.html"), name="password_reset"),

    #Where can I find OR set theses paths these values
    #2
    path('password_reset_done/',
        auth_views.PasswordResetDoneView.as_view(template_name="email_sent.html"),name="password_reset_done"),
    #3
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="reset.html"), name="password_reset_confirm"),

    #4
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="reset_complete.html"), name="password_reset_complete"),

    ]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import path
from main import views
urlpatterns = [
    path('',views.index,name='home'),
    path('about/',views.about,name='about'),
    path('services/',views.services,name='services'),
    path('contact/',views.contact,name='contact'),
    # path('tutorial/', views.tutindex, name ='tutindex'),

    # #tutorial
    # path('create_tut/',views.createtut,name='create_tut'),
    # path('update_tut/<slug:slug>/',views.updatetut, name='update_tut'),
    # path('delete_tut/<slug:slug>/',views.deletetut, name='delete_tut'),
    # path('<slug:slug>/',views.tut, name='slug'),



]

account/models.py
from django.db import models
from django.contrib.auth.models import User,auth

class Skill(models.Model):
    skillname = models.CharField(max_length=50,default="")
    def __str__(self):
        return self.skillname

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')
    skills = models.ManyToManyField(Skill, blank=True)
    dp = models.ImageField(upload_to="pics")
    phone = models.BigIntegerField(null=True, default=None)
    profession = models.CharField(max_length=50, null=True, default=None)
    experience = models.CharField(max_length=50, null=True, default=None)
    rate = models.IntegerField(null=True, default=None)
    eng_level = models.CharField(max_length=10, null=True, default=None)
    completedProjectNo = models.IntegerField(null=True, default=None)
    availability = models.IntegerField(null=True, default=None)
    bio = models.TextField(null=True, default=None)  # Changed to TextField for longer text
    twitter = models.URLField(null=True, blank=True)
    linkedin = models.URLField(null=True, blank=True)
    github = models.URLField(null=True, blank=True)
    def __str__(self):
        return self.user.username
    
    # def __str__(self):
    #     name = str(self.user.first_name)
    #     if self.user.last_name:
    #         name += ' ' + str(self.user.last_name)
    #     return name

main/models.py
from django.db import models
from django.db.models.fields import IntegerField
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils.text import slugify

# Create your models here.
class Contact(models.Model):
    name=models.CharField(max_length=122, default="")
    email=models.EmailField(max_length=122,primary_key=True)
    phone=models.BigIntegerField()
    desc=models.TextField()
    date=models.DateField()

    def __str__(self):
        return self.name



class Tutorial(models.Model):
    id=models.IntegerField(primary_key=True,default="")
    subject=models.CharField( default="xyz",max_length=100)
    img=models.ImageField( upload_to="images",height_field=None, width_field=None, max_length=None)
    sampleLink = models.URLField(blank=True, null=True )
    desc=RichTextUploadingField()
    price=models.IntegerField()
    offer=models.BooleanField()
    slug = models.SlugField(null=True, blank=True, default='tutorial')

    def __str__(self):
        return self.subject

    def save(self, *args, **kwargs):
        if self.slug == None:
            slug = slugify(self.headline)
            has_slug = Tutorial.objects.filter(slug=slug).exists()
            count = 1
            while has_slug:
                count += 1
                slug = slugify(self.headline) + '-' + str(count) 
                has_slug = Tutorial.objects.filter(slug=slug).exists()
            self.slug = slug
        super().save(*args, **kwargs)

class FrontPage(models.Model):
    title=models.CharField( primary_key=True,max_length=100,default=0)
    desc=models.CharField(max_length=150,default="")
    img=models.CharField(max_length=30,default="")
    minRead=models.IntegerField()
    def __str__(self):
        return self.title


class Crausal(models.Model):
    id=models.IntegerField(primary_key=True,default=0)
    title=models.CharField( max_length=50)
    img1=models.ImageField( upload_to='images', height_field=None, width_field=None, max_length=None)
    img2=models.CharField(max_length=50,default="mountain")
    ctext=models.CharField(max_length=100)
    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime,timezone
from django.utils.text import slugify
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
# Create your models here.


class Profile(models.Model):
	user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE, related_name='portfolio_profile')
	first_name = models.CharField(max_length=200, blank=True, null=True)
	last_name = models.CharField(max_length=200, blank=True, null=True)
	email = models.CharField(max_length=200)
	profile_pic = models.ImageField(null=True, blank=True, upload_to="images", default="/user.png")
	bio = models.TextField(null=True, blank=True)
	twitter = models.CharField(max_length=200,null=True, blank=True)

	def __str__(self):
		name = str(self.first_name)
		if self.last_name:
			name += ' ' + str(self.last_name)
		return name

class Tag(models.Model):
	name = models.CharField(max_length=200)

	def __str__(self):
		return self.name


class Post(models.Model):
	headline = models.CharField(max_length=200)
	sub_headline = models.CharField(max_length=200, null=True, blank=True)
	thumbnail = models.ImageField(null=True, blank=True, upload_to="images", default="/images/placeholder.png")
	body = RichTextUploadingField(null=True, blank=True)
	created = models.DateTimeField(auto_now_add=True)
	active = models.BooleanField(default=False)
	featured = models.BooleanField(default=False)
	tags = models.ManyToManyField(Tag, blank=True)
	slug = models.SlugField(null=True, blank=True)

	def __str__(self):
		return self.headline

	def save(self, *args, **kwargs):

		if self.slug == None:
			slug = slugify(self.headline)

			has_slug = Post.objects.filter(slug=slug).exists()
			count = 1
			while has_slug:
				count += 1
				slug = slugify(self.headline) + '-' + str(count) 
				has_slug = Post.objects.filter(slug=slug).exists()

			self.slug = slug

		super().save(*args, **kwargs)


class PostComment(models.Model):
	author = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
	post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True, blank=True)
	body = models.TextField(null=True, blank=True)
	created = models.DateTimeField(auto_now_add=True, null=True, blank=True)

	def __str__(self):
		return self.body

	@property
	def created_dynamic(self):
		now = timezone.now()
		return now
	

account/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile

class ProfileForm(ModelForm):
	class Meta:
		model = Profile
		fields = '__all__'
		exclude = ['user']

portfolio/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Post, Profile


class CustomUserCreationForm(UserCreationForm):

	class Meta:
		model = User
		fields = ['first_name', 'last_name', 'email', 'password1', 'password2']

class PostForm(ModelForm):

	class Meta:
		model = Post
		fields = '__all__'

		widgets = {
			'tags':forms.CheckboxSelectMultiple(),
		}

class UserForm(ModelForm):
	class Meta:
		model = User
		fields = ['first_name', 'last_name', 'email']
		

class ProfileForm(ModelForm):
	class Meta:
		model = Profile
		fields = '__all__'
		exclude = ['user']

account/views.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.contrib.auth.models import User,auth
from django.contrib.auth import authenticate,login,logout
# from account.models import Skill,WorkLink #,Profile

# Create your views here.
def register(request):
    if request.method == 'POST':
        first_name =request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        username = request.POST.get('username')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        email = request.POST.get('email')
        if password1 == password2:
            if User.objects.filter(username=username).exists():
                print("usernametaken")
                messages.error(request,"Username taken")
                return redirect('/account/register/')
            elif User.objects.filter(email=email).exists():
                print("email taken")
                messages.error(request,"Email taken")
                return redirect('/account/register/')
            else:
                user=User.objects.create_user(username=username, password=password1, email=email, first_name=first_name, last_name=last_name)
                user.save()
                print('user created')
                messages.error(request,"User account created successfully!!!")
                return redirect('/account/login/')
        else:
            print("password not matching")
            messages.info(request,"password not matching")
        return redirect('/account/register/')

    else:
        return render(request,"account/register.html")



def login_(request):
    if request.method=="POST":
        # u= request.POST['username']
        # p=request.POST['password']
        username= request.POST.get("username")
        password=request.POST.get("password")
        print(username,password)
        #check if user have entered correct credentials
        user = authenticate(username=username,password=password)

        print(request.user)
        if user is not None:
            login(request,user)
            return redirect('/')
        else:
            print("error ho gyi babu")
            messages.info(request,"invalid credentials")
            return redirect('/account/login/')

    else:
        return render(request,"account/login.html")


def logout_(request):
    logout(request)
    return redirect('/')

main/views.py
from django.shortcuts import render, HttpResponse,redirect
from django.http import HttpResponse
from datetime import datetime
from main.models import Contact, Tutorial, FrontPage, Crausal
from django.contrib import messages


def index(request):
    # contests=Contest.objects.all()
    front=FrontPage.objects.all()
    carousels=Crausal.objects.all()
    return render(request, 'main/index.html',{'front':front,'carousels':carousels})


def tutindex(request):
    tuts=Tutorial.objects.all()
    return render(request,'main/tutindex.html', {'tuts':tuts} )


# # #CRUD VIEWS
# @admin_only
# @login_required(login_url="account/login")
# def createBlog(request):
# 	form = BlogForm()
	
# 	if request.method == 'POST':
# 		form = BlogForm(request.POST, request.FILES)
# 		if form.is_valid():
# 			form.save()
# 		return redirect('blogs')

# 	context = {'form':form}
# 	return render(request, 'blog/blog_form.html', context)

# def fuck(request):
# 	return render(request, 'blog/delete.html')
	


# @admin_only
# @login_required(login_url="account/login")
# def updateBlog(request, slug):
# 	post = Tutorial.objects.get(slug=slug)
# 	form = BlogForm(instance=post)
# 	try:
# 		if request.method == 'POST':
# 			form = BlogForm(request.POST, request.FILES, instance=post)
# 			if form.is_valid():
# 				form.save()
# 			return redirect('blogs')
# 	except Tutorial.DoesNotExist:
# 		return Http404("Post does not exist")

# 	context = {'form':form}
# 	return render(request, 'blog/blog_form.html', context)


# @admin_only
# @login_required(login_url="account/login")
# def deleteBlog(request, slug):
# 	post = Tutorial.objects.get(slug=slug)

# 	if request.method == 'POST':
# 		post.delete()
# 		return redirect('blogs')
# 	context = {'item':post}
# 	return render(request, 'blog/delete.html', context)





def about(request):
    return render(request, 'main/about.html')

def services(request):
    services= Tutorial.objects.all()
    return render(request, 'main/services.html',{'services':services})

def contact(request):
    if  request.method=="POST":
        name=request.POST.get('name')
        email=request.POST.get('email')
        phone=request.POST.get("phone")
        desc=request.POST.get('desc')
        contact=Contact(name=name,email=email,phone=phone,desc=desc,date=datetime.today())
        contact.save()
        messages.success(request, "your message have been sent...!!")
    return render(request, 'main/contact.html')
    #return HttpResponse("this is contact page")

def projects(request):
    return render(request,'main/projects.html')

portfolio/templates/portfolio/account.html
{% extends 'base.html'%}
{% load static %}
{% block title %} HOME{% endblock title %}

{% block body %}
<style type="text/css">
	#user_pic{
		height: 200px;
		width: 200px;
		border-radius: 50%;
		border:5px solid #888;
		margin:0 auto;
		object-fit: cover;
	}

	#user-info-box{
		text-align: center;
	}
</style>

<div class="main-container">
	<br>
	<div class="row">
		<div class="col-md-4">
			<div class="card card-body" id="user-info-box">
				{% comment %} <img id="user_pic" src="{{request.scheme}}://{{request.META.HTTP_HOST}}/static/images/{{profile.dp}}"> {% endcomment %}
				<img id="user_pic" src="{{profile.dp.url}}">
				<br>
				<h2>{{profile}}</h2>
				<p>Email: {{request.user.email}}</p>
				<hr>
				<p>{{profile.bio}}</p>
				<hr>
				<a class="btn btn-info btn-block" href="{% url 'update_profile' %}">Edit Profile</a>
			</div>
		</div>
		<div class="col-md-8">
			<div class="card card-body">
				<h3>My Orders:</h3>
				<hr>
				<table class="table">
					<thead class="thead-dark">
						<tr>
							<th>Transaction ID</th>
							<th>Date</th>
							<th>Items</th>
							<th>Total</th>
							<th></th>
						</tr>
					</thead>
					<tr>
						<td>122523462</td>
						<td>11-24-2020</td>
						<td>2</td>
						<td>$12.18</td>
						<td><a class="btn btn-dark btn-sm" href="">View Order</a></td>
					</tr>

					<tr>
						<td>122523123</td>
						<td>11-29-2020</td>
						<td>7</td>
						<td>$53.65</td>
						<td><a class="btn btn-dark btn-sm" href="">View Order</a></td>
					</tr>
				</table>
			</div>
		</div>
	</div>
</div>

{% endblock body %}

portfolio/templates/portfolio/delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="main-container">
	<form method="POST" action="">
		{% csrf_token %}

		<p>Are you sure you want to delete {{item}}?</p>
		<a class="btn btn-primary" href="{% url 'posts' %}">&laquo Back to Posts</a>
		<input class="btn btn-danger" type="submit" value="Confirm">
	</form>
</div>

{% endblock content %}

portfolio/templates/portfolio/email_sent.html
{% extends 'pbase.html' %}

{% block content %}

<style type="text/css">
	html, body{
		height: 100%;
	}

	#page-wrapper{
		height: 100%;
		display: flex;
		justify-content: center;
		align-items: center;
		text-align: center;
		background-color: #eaeaea;
	}

	#success-box{
		max-width: 800px;
		height: auto;
		background-color: #fff;
		border:1px solid #888;
		border-radius: 5px;
		padding: 15px;
	}

	#success-box p{
		font-size: 18px;
	}

</style>

<div id="page-wrapper">
	<div id="success-box" class="content-block">
		<h1>Thanks for reaching out!</h1>
		<p>Your message was successfully sent. I will do my best to get back to you in a timely manner :)</p>
		<a id="back-btn" class="btn btn-success" href="{% url 'home' %}">BACK TO HOME PAGE</a>
	</div>
</div>

{% endblock content %}

portfolio/templates/portfolio/email_template.html
{{message}}

{{name}}

{{email}}

portfolio/templates/portfolio/index.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>ALOK</title>

	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-47692315-56"></script>
	<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'UA-47692315-56');
	</script>


	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

	<link href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">

	<link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@500&family=Russo+One&display=swap" rel="stylesheet">

	<link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}">
	<link id="theme-style" rel="stylesheet" type="text/css" href="">
</head>
<body>

	<section class="s1">
		<div class="main-container">
			<div class="greeting-wrapper">
				<h1>Hi, I'm {{request.user.first_name}} {{request.user.last_name}}</h1>
			</div>


			<div class="intro-wrapper">
				{% include 'portfolio/navbar.html' %}

				<div class="left-column">
					<img id="profile_pic" src="{% static 'images/alokDP.jpg' %}">
					<h5 style="text-align: center;line-height: 0;">Personalize Theme</h5>

					<div id="theme-options-wrapper">
						<div data-mode="light" id="light-mode" class="theme-dot"></div>
						<div data-mode="blue" id="blue-mode" class="theme-dot"></div>
						<div data-mode="green" id="green-mode" class="theme-dot"></div>
						<div data-mode="purple" id="purple-mode" class="theme-dot"></div>
					</div>

					<p id="settings-note">*Theme settings will be saved for<br>your next visit</p>
				</div>

				<div class="right-column">

					<div id="preview-shadow">
						<div id="preview">
							<div id="corner-tl" class="corner"></div>
							<div id="corner-tr" class="corner"></div>
							<h3>What I Do</h3>
							<p>I am a lead developer in present life, I enjoy development and coffee.</p>
							<div id="corner-br" class="corner"></div>
							<div id="corner-bl" class="corner"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section class="s2">
		<div class="main-container">

			<div class="about-wrapper">
				<div class="about-me">
					<h4>More about me</h4>
					<p>{{user_profile.bio}}<p>
					<p>I build new projects just to tickle my brain and love teaching my fellows how they're made.</p>

					<p>While I keep busy learning new skills, I love to meet new people in search of a great team & projects that interest me.</p>


					<hr>

					<h4>TOP EXPERTISE</h4>

					<p>Fullstack developer with primary focus on Django + Machine learning:
					<a target="_blank" href="{% static 'alokResume.pdf' %}">Download Resume</a>
					</p>

					<div id="skills">
							<ul>
								{% for skill in skills_column1 %}
									<li>{{skill}}</li>
								{% endfor %}
							</ul>
							<ul>
								{% for skill in skills_column2 %}
									<li>{{skill}}</li>
								{% endfor %}
							</ul>


						{% comment %} <ul>
							{% for skill in user_profile.skills.all  %}
								<li>{{skill}}</li>
							{% endfor %}
						<ul> {% endcomment %}
						{% comment %} <ul>
							<li>Python</li>
							<li>Django</li>
							<li>Machine learning</li>
							<li>Mysql</li>
							<li>mongoDB</li>
						</ul>

						<ul>
							<li>Django rest API</li>
							<li>C++/C</li>
							<li>AWS (sagmaker/S3/EC2)</li>
							<li>Git/Github/Heroku</li>
							<li>HTML/CSS/Bootstrap</li>
						</ul> {% endcomment %}

					</div>

				</div>


				<div class="social-links">
					<img id="social_img" src="{% static 'images/alok.jpg' %}">
					<h3>Find me on Twitter & Linkdein</h3>

					<a target="_blank" href="{{user_profile.linkedin}}">Linkedin: @alokknight</a>
					<br>
					<a target="_blank" href="{{user_profile.twitter}}">Twitter: @aalokknight</a>
				</div>
			</div>

		</div>
	</section>

	<section class="s1">
		<div class="main-container">
			<h3 style="text-align: center;">Want to see some of my past projects</h3>

			<div class="post-wrapper">

				{% for project in posts %}
				<div>
					<div class="post">
						<img class="thumbnail" src="{{ project.img.url }}">
						<div class="post-preview">
							<h6 class="post-title">{{project.title}}</h6>
							{% comment %} <p class="post-intro">{{project.desc|safe}}</p> {% endcomment %}
							{% comment %} <a href="{%  url 'projects' project.slug %}">Read More</a> {% endcomment %}
							<button type="button" onclick="window.location.href='#'"class="btn btn-sm btn-outline-secondary">Git</button>
                            <button type="button" onclick="window.location.href='/projects/{{project.slug}}'" class="btn btn-sm btn-outline-secondary">View</button>
						</div>
					</div>
				</div>
				{% endfor %}

			</div>

			<p align="center">
				<a href="{% url 'projects' %}">View more</a>
			</p>
		</div>
	</section>

	<section class="s2">
		<div class="main-container">
			<a href=""></a>
			<h3 style="text-align: center;">Get In Touch</h3>

			<form id="contact-form" method="POST" action="{% url 'send_email' %}">
				{% csrf_token %}
				<a name="contact"></a>

				<label>Name</label>
				<input required class="input-field" type="text" name="name">

				<label>Subject</label>
				<input required class="input-field" type="text" name="subject">

				<label>Email</label>
				<input required class="input-field" type="text" name="email">

				<label>Message</label>
				<textarea required class="input-field" name="message"></textarea>

				<input id="submit-btn" type="submit" value="Send">
			</form>
		</div>
	</section>

	<script type="text/javascript">
		let static = "{% static 'css' %}"
	</script>

	<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
</body>
</html>

portfolio/templates/portfolio/login.html
{% include 'base.html' %}
{% load static %}
{% block body %}


<section id="login-page-wrapper">
	<div id="login-form-wrapper">
		{% if messages %}
			{% for message in messages %}
				{% if message.tags == 'success' %}
					<div class="alert alert-success" role="alert">
						<span>{{message}}</span>					
					</div>
				{% elif message.tags == 'error' %}
					<div class="alert alert-danger" role="alert">
						<span>{{message}}</span>					
					</div>
				{% endif %}
			{% endfor %}
		{% endif %}

		<h3 style="text-align: center">Member Login</h3>
		<hr>
		<form method="POST">
			{% csrf_token %}
			<label>Email</label>
			<input class="form-control" type="email" name="email">
			<br>
			<label>Password</label>
			<input class="form-control" type="password" name="password">
			<br>
			<input class="btn btn-primary btn-lg btn-block" type="submit" value="Login">
		</form>

		<br>
		<p>Dont have an account? <a href="{% url 'register' %}">Register</a></p>
		<p>Forgot your password? <a href="{% url 'password_reset' %}">Reset</a></p>
	</div>
</section>

{% endblock body %}

portfolio/templates/portfolio/posts.html
{% include 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}


<style type="text/css">
	#div_id_tags, #id_tags{
		overflow-y: scroll;
		max-height: 100px;
		border-radius: 5px;
		padding: 5px;
		border:1px solid #888;
	}
</style>

<div class="main-container">
	<h1>Posts</h1>
	{% if request.user.is_staff %}
		<a class="btn btn-warning" href="{% url 'create_post' %}">Create Post</a>
	{% endif %}
	<form id="searchForm" method="GET">
		{{myFilter.form|crispy}}
		
		<input class="btn btn-primary" type="submit" value="search">
	</form>
	<br>
	<div class="post-wrapper">
		{% for post in posts %}
		<div>
			<div class="post">
				<img class="thumbnail" src="{{post.thumbnail.url}}">
				<div class="post-preview">
					<h6 class="post-title">{{post.headline}}</h6>
					<p class="post-intro">{{post.sub_headline}}</p>
					<a href="{% url 'post' post.slug %}">Read More</a>

					{% if request.user.is_staff %}
						| <a href="{% url 'update_post' post.slug %}">Edit</a>
						| <a href="{% url 'delete_post' post.slug %}">Delete</a>
					{% endif %}
					<hr>
					{% for tag in post.tags.all %}
						<span class="tag">{{tag}}</span>
					{% endfor %}
				</div>
			</div>
		</div>
		{% empty %}
			<h3>No posts found...</h3>
		{% endfor %}
	</div>

	<div class="row">
		
		{% if posts.has_other_pages %}

			<ul class="pagination">

				{% if posts.has_previous %}
					<li class="page-item"><a data-page="{{posts.previous_page_number}}" href="?page={{posts.previous_page_number}}" class="page-link">&laquo</a></li>

					<li class="page-item"><a data-page="1" href="?page=1" class="page-link">First</a></li>
				{% endif %}


				{% for i in posts.paginator.page_range %}
					{% if posts.number == i %}
						<li class="page-item"><a class="active page-link">{{i}}</a></li>
					{% else %}
						<li class="page-item"><a data-page="{{i}}" href="?page={{i}}" class="page-link">{{i}}</a></li>
					{% endif %}
					
				{% endfor %}


				{% if posts.has_next %}
					<li class="page-item"><a data-page="{{posts.paginator.num_pages}}" href="?page={{posts.paginator.num_pages}}" class="page-link">Last</a></li>

					<li class="page-item"><a data-page="{{posts.next_page_number}}" href="?page={{posts.next_page_number}}" class="page-link">&raquo</a></li>
				{% endif %}
			</ul>

		{% endif %}
	</div>
</div>


<script type="text/javascript">
	let searchForm = document.getElementById('searchForm')
	let pageLinks = document.getElementsByClassName('page-link')

	for(var i=0; pageLinks.length > i; i++){

		pageLinks[i].addEventListener('click', function(e){
			e.preventDefault()
			let page = this.dataset.page
			console.log('Page:', page)
			searchForm.innerHTML += `<input value="${page}" name="page" hidden >`
			searchForm.submit()
		})

	}
</script>

{% endblock body %}